#include <SFML/Graphics.hpp>
#include <tuple>
#include <vector>
#include "physic/cinematic.hpp"
#include "physic/hitbox.hpp"
#include "physic/collision.hpp"
#include "physic/step.hpp"
#include "terrain.hpp"
#include "entity.hpp"
#include "render.hpp"
